In [3]:
import numpy as np

In [2]:
# 3
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr3.size * arr3.itemsize

80

In [6]:
# 5
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.\n    If ``x1.shape != x2.shape``, they must be broadcastable to a common\n    shape (which becomes the shape of the output).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or None,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    This condition is broadcast over the input. At locations where the\n    condition is True, the `out` array will be set to the ufunc result.\n    Elsewhere, the `out` array will retain its original value.\n    Note that if an uninitialized `out` array is created via the defau

In [7]:
# 6
arr6 = np.zeros(10)
arr6[4] = 1
arr6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
# 7 
arr7 = np.arange(10, 50)
arr7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
# 8
arr7[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
# 9
arr9 = np.arange(0, 9).reshape(3, 3)
arr9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# 10

arr10 = [1, 2, 0, 0, 4, 0]
np.nonzero(arr10)

(array([0, 1, 4]),)

In [9]:
arr11 = np.ones(9).reshape(3,3)
arr11

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr12 = np.random.random((3,3,3))
arr12

array([[[0.05081898, 0.49945813, 0.96172354],
        [0.488703  , 0.43472602, 0.16432559],
        [0.60559174, 0.87813558, 0.7658127 ]],

       [[0.14077545, 0.15844241, 0.13194952],
        [0.2206243 , 0.16983499, 0.02329713],
        [0.90098772, 0.47553198, 0.52936861]],

       [[0.87418121, 0.44555173, 0.65239515],
        [0.95903827, 0.85407313, 0.61687185],
        [0.64839573, 0.39783462, 0.88876101]]])

In [16]:
arr13 = np.random.random((10,10))
print(arr13.min())
print(arr13.max())

0.0017143215067787487
0.9977847074410428


In [17]:
arr14 = np.random.random(30)
arr14.mean()

np.float64(0.4957634905899776)

In [ ]:
arr15 = np.ones((5,5))
arr15[1:-1, 1:-1] = 0
arr15

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.pad(arr15, pad_width=1, mode="constant", constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [31]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [33]:
arr18 = np.diag([1,2,3,4], k=-1)
arr18

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [48]:
arr19 = np.zeros((8,8), dtype=int)
arr19[1::2, ::2] = 1
arr19[::2, 1::2] = 1
arr19

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])