In [2]:
import numpy as np


In [2]:
# 1
a = np.arange(20)
print(a[5])
print(a[-3])
print(a[::2])
print(a[::-1])

5
17
[ 0  2  4  6  8 10 12 14 16 18]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [4]:
# 2
b = np.arange(50, 101, 5)
print(b)
print(b.sum())
print(b.mean())

[ 50  55  60  65  70  75  80  85  90  95 100]
825
75.0


In [16]:
# 3
c = np.random.randint(10, 99, 20)
print(c[(c % 2 == 0)])

[24 50 22 78 94 34 78 90]


In [18]:
# 4

d = np.linspace(0, 1, 10)
print(d[3:8])
print(d)

[0.33333333 0.44444444 0.55555556 0.66666667 0.77777778]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [7]:
# 5
e = np.arange(1, 31).reshape(5, 6)
print(e[1])
print(e[:,-1])
print(e[1:4, 2:5])

[ 7  8  9 10 11 12]
[ 6 12 18 24 30]
[[ 9 10 11]
 [15 16 17]
 [21 22 23]]


In [9]:
#6 

A = np.arange(1, 10).reshape(3, 3)
I = np.eye(3)
C = A @ I 
print(np.allclose(A, C))

True


In [10]:
# 7

B = np.arange(9).reshape(3, 3)
v = np.array([1, 2, 3])

print(B @ v)
print(v @ B)

[ 8 26 44]
[24 30 36]


In [25]:
# 8

M = np.arange(16).reshape(4,4)
print(np.trace(M))
indexes = np.where(M > M.mean())
print(np.sum(M[indexes]))

30
92


In [30]:
# 9
Z = np.random.uniform(0, 10, (3,4))
mask = Z > 5
Z[mask] = np.pow(Z[mask], 2)
print(Z)

[[96.54407208 47.47879081  1.76329252  3.89476329]
 [82.69851162 56.31804953 96.3396707   4.69858127]
 [38.61995661 33.82503357 81.30926981  4.72338282]]


In [22]:
# 10

X = np.arange(1, 10).reshape(3, 3)
print(X)
print(np.linalg.det(X))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [23]:
# 11
X = np.random.random(50)
print(X.mean())
print(X.min())
print(X.max())

0.5310216943066205
0.04915105914767248
0.9595974221201301


In [26]:
# 12
X = np.random.uniform(0, 1, 50)
print(np.mean(np.abs(X)))

0.5566834330005709


In [27]:
# 13
x = np.random.random(20)
print(np.std(x))
print(np.var(x))

0.3254622057465622
0.10592564736941759


In [28]:
# 14

M = np.random.uniform(0, 100, (4,4))
M_norm = (M - M.min()) / (M.max() - M.min() + 1e-12)
print(M_norm)

[[0.37617768 0.69287348 0.19079621 0.        ]
 [0.97073689 0.579616   0.15788347 0.93253764]
 [0.26551468 0.01178452 0.07524525 1.        ]
 [0.52398127 0.98605221 0.80711443 0.77773441]]


In [29]:
# 15
X = np.random.random((6,6))
X[X < 0.25] = 0
print(X)

[[0.43699568 0.82339731 0.68917232 0.         0.66861179 0.        ]
 [0.61864607 0.29031946 0.71171071 0.79459484 0.62667578 0.4121557 ]
 [0.67257662 0.         0.35211837 0.         0.92170901 0.31889544]
 [0.3006497  0.         0.3301598  0.         0.63730866 0.        ]
 [0.28893045 0.         0.62031304 0.60741778 0.66173294 0.78005173]
 [0.34245386 0.         0.         0.55498443 0.         0.86863888]]


In [ ]:

# 16
a = np.arange(10)

print(a[a % 2 == 0].sum())  

20


In [47]:
# 17
X = np.random.randn(10)
filtered = X[X > 0]
size = filtered.size
print(size)

5


In [48]:
# 18
M = np.random.uniform(0, 10, (3,4))
indexes = np.where(M > 5)
np.pow(M[indexes], 2)
print(M)

[[8.14345859 2.46411724 2.41770342 7.22270384]
 [7.57464598 9.99073616 1.60325866 3.57729034]
 [7.8028633  8.03636725 9.87358298 5.91192789]]


In [32]:
# 19
M = np.arange(1,26).reshape(5,5)
# modify diagonal in-place
np.fill_diagonal(M, 0)
print(M)

[[ 0  2  3  4  5]
 [ 6  0  8  9 10]
 [11 12  0 14 15]
 [16 17 18  0 20]
 [21 22 23 24  0]]


In [46]:
# 20 
M = np.random.randint(0,10,(4,4))
mask = M == 0
value = M[mask == False].mean()
print(M)
M[mask] = value
print(M)

[[4 9 2 7]
 [5 1 8 1]
 [5 0 7 6]
 [2 7 3 8]]
[[4 9 2 7]
 [5 1 8 1]
 [5 5 7 6]
 [2 7 3 8]]


In [6]:
# 21

X = np.random.random((5,5))
K = np.ones((3,3))

def convolve2d(X, K):
    x_rows, x_cols = X.shape
    k_rows, k_cols = K.shape
    output_rows = x_rows - k_rows + 1
    output_cols = x_cols - k_cols + 1
    output = np.zeros((output_rows, output_cols))
    for i in range(output_rows):
        for j in range(output_cols):
            output[i, j] = np.sum(X[i:i+k_rows, j:j+k_cols] * K)
    return output

print(convolve2d(X, K))

[[3.18904869 4.1909773  5.05851058]
 [2.98839575 3.14461196 4.11286866]
 [2.73803393 2.40584207 3.65287463]]


In [54]:
# 22

X = np.random.random((6,6))

pool_size = 2

Y = X.reshape(X.shape[0]//pool_size, pool_size, X.shape[1]//pool_size, pool_size).mean(axis=(1,3))

print(Y)

[[0.64326449 0.44976063 0.43337036]
 [0.66662382 0.45019833 0.42802194]
 [0.5643483  0.64016473 0.54073598]]


In [4]:
# 23

X = np.random.random(20)
window = 3

cumsum = np.cumsum(np.insert(X, 0, 0))

moving_averages = (cumsum[window:] - cumsum[:-window]) / window

print(moving_averages)

[0.4537707  0.65281664 0.6372615  0.66678621 0.48965894 0.47217603
 0.4586263  0.69785372 0.84316384 0.80945235 0.68589351 0.71071298
 0.74095391 0.71577734 0.51543315 0.31588014 0.16523141 0.09264509]


In [51]:
# 24

A = np.random.randint(0, 10, (10, 3, 3))
B = np.random.randint(0, 10, (10, 3, 3))

C = np.matmul(A, B)
print(C)

[[[ 13  17  18]
  [ 51 120 109]
  [ 75  85  76]]

 [[ 63 128 112]
  [ 34  51  46]
  [ 92 114 108]]

 [[ 40  24  64]
  [ 61  18  45]
  [ 51  36  83]]

 [[ 42  43  35]
  [ 36  48  24]
  [130 114  68]]

 [[ 23  66  50]
  [ 66  45  50]
  [ 49  73  70]]

 [[ 99  66  84]
  [125 111 128]
  [118 110 116]]

 [[ 63  85  43]
  [ 24  48  30]
  [ 61  95  56]]

 [[ 38  74  36]
  [ 38  76  44]
  [ 48 132 111]]

 [[ 70  23 168]
  [ 44   5  64]
  [ 13   7  43]]

 [[ 24  24  97]
  [ 48  22  67]
  [ 16  12  35]]]


In [53]:
# 25

M = np.random.randint(0, 10, (5, 5))
window = (3,3)

view = np.lib.stride_tricks.sliding_window_view(M, window_shape=window)
block_sums = view.sum(axis=(2,3))
print(block_sums)

[[46 44 41]
 [38 47 45]
 [43 42 41]]


In [2]:
import numpy as np
# 26

I = np.random.random((6, 6))

F = np.array([[0, 1, 0],
              [1, -4, 1],
              [0, 1, 0]])

def convolve2d(I, F):
    i_rows, i_cols = I.shape
    f_rows, f_cols = F.shape
    output_rows = i_rows - f_rows + 1
    output_cols = i_cols - f_cols + 1
    output = np.zeros((output_rows, output_cols))
    for i in range(output_rows):
        for j in range(output_cols):
            output[i,j] = np.sum(I[i:i+f_rows, j:j+f_cols] * F)
    
    return output

L = convolve2d(I, F)
print(L)

[[ 1.15974965 -0.55115656  2.13636015 -1.74127018]
 [-0.25412459 -0.85007122  0.96263849  0.01435035]
 [-0.37207384  0.87492425  0.48600144 -2.58134377]
 [ 0.8998473   1.34432058 -1.32863742  1.36867514]]


In [3]:
# 26

M = np.random.random((9, 9))

window = 3

pooled = M.reshape(M.shape[0]//window, window, M.shape[1]//window, window).mean(axis=(1,3))
print(pooled)



[[0.40020434 0.49086845 0.57220275]
 [0.52752688 0.50503095 0.59699285]
 [0.66839817 0.37369628 0.69887211]]


In [36]:
# 28 - averaging with moving window

x = np.random.normal(size=50)

window = 5
cumsum = np.cumsum(np.insert(x, 0, 0))
moving_averages = np.convolve(x, np.ones(window)/window, mode='valid')
print(moving_averages)



[-0.47066197  0.16688904  0.12903354 -0.2436677  -0.18682476 -0.09454121
 -0.39777728 -0.78436641 -0.63368033 -0.3842992  -0.3373497  -0.02034693
  0.42116078  0.33229213  0.59076447  0.55341061  0.28503084  0.26713327
  0.02642426  0.04002991 -0.18830822 -0.11313326 -0.05135037  0.13371176
 -0.11239892 -0.03686601  0.16299406 -0.23217358 -0.06155907  0.0648656
  0.31473285 -0.10055866  0.26018675  0.33990983 -0.03995436 -0.19448154
 -0.13481287 -0.46172578 -0.51332093 -0.18520038 -0.32337389 -0.06751192
 -0.14177845 -0.34302731 -0.61707581 -0.43610503]


In [24]:
# 29

A = np.random.randint(0, 10, (5, 2, 3))
B = np.random.randint(0, 10, (5, 4, 3))

# transpose B's last two axes so shapes become (5,2,3) @ (5,3,4) -> (5,2,4)
R = np.matmul(A, B.transpose(0, 2, 1))
print(R.shape)

(5, 2, 4)


In [27]:
img = np.random.uniform(0, 10,(8, 8))

window = (4, 4)

view = np.lib.stride_tricks.sliding_window_view(img, window_shape=window)
sum = view.sum(axis=(-2, -1))
print(sum)


[[83.26258362 71.46947359 82.8824889  85.61462666 82.60452375]
 [88.1328436  65.3219691  67.20276936 66.63113119 64.86916389]
 [84.94552779 61.1534571  64.02912264 62.94666419 56.71235733]
 [76.82902996 59.37289341 61.42015958 58.04262591 52.15294988]
 [76.08111964 63.57226892 60.49737857 59.49621195 47.30144504]]
