In [3]:
import numpy as np

# Zadanie 1
Z = np.arange(0, 50)
print(Z[0])
print(Z[-1])
print (Z[3:8])
print(Z[::-1])




0
49
[3 4 5 6 7]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [25]:
# 2

A = np.arange(0, 9).reshape(3,3)
I = np.eye(3)

C = A @ I
print(C)
print(np.allclose(A, C))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
True


In [10]:
# 3 

Z = np.random.uniform(0, 1, 30)
print(Z.mean())
print(Z.min())
print(Z.max())

0.5001042328672956
0.004839168341472799
0.9879640566265837


In [22]:
# 4

M = np.random.random((5,5))
M_norm = (M - M.min()) / (M.max() - M.min() + 1e-12)
print(M_norm)
M_norm[(M_norm < 0.2)] = 0
print(M_norm)

[[0.15272682 0.14809752 0.99681928 0.15807422 0.20585079]
 [0.52559519 0.10111437 0.73398085 0.03722809 0.84675929]
 [0.43630107 0.51566051 0.44973645 1.         0.        ]
 [0.01276564 0.46302852 0.34110091 0.55150445 0.46818249]
 [0.29767748 0.44735015 0.38987962 0.92494674 0.61097469]]
[[0.         0.         0.99681928 0.         0.20585079]
 [0.52559519 0.         0.73398085 0.         0.84675929]
 [0.43630107 0.51566051 0.44973645 1.         0.        ]
 [0.         0.46302852 0.34110091 0.55150445 0.46818249]
 [0.29767748 0.44735015 0.38987962 0.92494674 0.61097469]]
