In [2]:
import numpy as np

In [2]:
Z1 = np.arange(10, 50)
print(Z1[0])
print(Z1[-1])
print(Z1[3:8])
print(Z1[::-1])

10
49
[13 14 15 16 17]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
A = np.arange(3*3).reshape(3,3)
I = np.eye(3)
C = np.matmul(A, I)
print(np.allclose(A, C))
print(A)

True
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
Z = np.random.random(30)
print(np.mean(Z))
print(np.min(Z))
print(np.max(Z))

0.482811756623888
0.01808085012977001
0.9379260920686209


In [3]:
M = np.random.random((5,5))
M_norm = (M - M.min()) / (M.max() - M.min() + 1e-12)
M_norm[(M_norm < 0.20)] = 0
print(M_norm)


[[1.         0.88258054 0.4701013  0.67669682 0.96755047]
 [0.73707831 0.53667492 0.70839566 0.27271769 0.        ]
 [0.         0.         0.         0.25951658 0.79378056]
 [0.46018646 0.60832041 0.86433399 0.34627715 0.21352563]
 [0.99815767 0.62825399 0.49691918 0.58171891 0.97921133]]


In [7]:
# 

from numpy.lib.stride_tricks import sliding_window_view

img = np.arange(1, 26).reshape(5, 5)
windows = sliding_window_view(img, (3, 3))
sums = windows.sum(axis=(-1, -2))

print("Obraz:\n", img)
print("Suma okien 3x3:\n", sums)



Obraz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Suma okien 3x3:
 [[ 63  72  81]
 [108 117 126]
 [153 162 171]]


In [8]:
# Średnia krocząca 1D

x = np.arange(10)
window = 3

# Suma przesuwna
cumsum = np.cumsum(np.insert(x, 0, 0))
moving_avg = (cumsum[window:] - cumsum[:-window]) / window

print("Średnia krocząca:", moving_avg)


Średnia krocząca: [1. 2. 3. 4. 5. 6. 7. 8.]


In [12]:
import numpy as np

# Przykładowa macierz (np. "obraz")
X = np.arange(25).reshape(5, 5)

# Rozmiar okna kroczącego
window = 3

# Tworzymy okna 3x3 przesuwane po macierzy
windows = np.lib.stride_tricks.sliding_window_view(X, (window, window))

# Liczymy średnią w każdym oknie
moving_avg_2d = windows.mean(axis=(2, 3))

print("Macierz wejściowa:\n", X)
print("\nŚrednia krocząca 2D (okno 3x3):\n", moving_avg_2d)


Macierz wejściowa:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Średnia krocząca 2D (okno 3x3):
 [[ 6.  7.  8.]
 [11. 12. 13.]
 [16. 17. 18.]]
